spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/matheus-entregas?createDataBaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
